# Generated by Django 4.0.3 on 2022-08-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addlist',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='addlist',
            name='text',
        ),
        migrations.AddField(
            model_name='addlist',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
